# Generated by Django 4.0.4 on 2022-05-15 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_tipocarrito_delete_tipocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=40)),
                ('precioProducto', models.IntegerField()),
                ('stockProducto', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos_carrito')),
            ],
            options={
                'db_table': 'db_producto_carrito',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='tipo',
            field=models.CharField(max_length=25),
        ),
    ]
