# Generated by Django 4.0.1 on 2022-05-16 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipousuario_registrousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousuario',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrousuario',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
