# Generated by Django 4.0.4 on 2022-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_imagenproducto_delete_imagenproductos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('username', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('suscripcion1', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'db_suscripcion',
            },
        ),
    ]
